### ISSUE TITLE
TripRequest not working

### ISSUE THREAD

**Issue by iKK001** [openTdataCH/ojp-js#29]
I tried your `ojp-js` library. Great work by the way !!

And unfortunately, I am still doing something wrong, possibly, when trying to get a TripRequest.

Maybe you can help me.

Here is my example code : 

```
import * as OJP from "ojp-sdk"

const fromLoc = OJP.Location.initWithStopPlaceRef("8507000", "Bern")
const toLoc = OJP.Location.initWithStopPlaceRef("8503000", "Zurich")
const fromLocation = new OJP.TripLocationPoint(fromLoc)
const toLocation = new OJP.TripLocationPoint(toLoc)

const tripRequestParams = OJP.TripsRequestParams.initWithLocationsAndDate(
    fromLocation,
    toLocation,
    new Date(),
)

if (tripRequestParams) {
    const stage = {
        key: "SBB",
        apiEndpoint: "https://api.opentransportdata.swiss/ojp2020",
        authBearerKey:
            "57c5dbbbf1fe4d0001000018e0f7158cb2b347e3a6745e3ef949e7bf",
    }
    const tripRequest = new OJP.TripRequest(stage, tripRequestParams)
    console.log("hmmmmmmmmm 1")
    tripRequest.fetchResponse((responseText: any, errorData: any) => {
        console.log("hmmmmmmmmm 2")
        if (errorData) {
            console.error(errorData)
        }
        console.log(responseText)
    })
}
```

And here is the error log:

```
[BUILD] hmmmmmmmmm 1
[BUILD] <userDir>/test/node_modules/ojp-sdk/lib/trips/trips-response.js:12
[BUILD]         const responseXML = new DOMParser().parseFromString(responseXMLText, 'application/xml');
[BUILD]                             ^
[BUILD] 
[BUILD] ReferenceError: DOMParser is not defined
[BUILD]     at Function.initWithXML (<userDir>/test/node_modules/ojp-sdk/lib/trips/trips-response.js:12:29)
[BUILD]     at <anonymous> (<userDir>/test/node_modules/ojp-sdk/lib/request/trips-request/trips-request.js:14:49)
[BUILD]     at <anonymous> (<userDir>/test/node_modules/ojp-sdk/lib/request/base-request.js:61:17)
[BUILD]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[BUILD] yarn tsx src/index.ts exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It obviously asks for a `DOMParser()` - but what does that mean ?

I do not want to make a frontend-App. But rather use it inside a Raspberry Pi or similar simply to get trips from A to B.

**Comment by iKK001** [comment]
I have a workaround:

If you add the following, then it works!

```
import jsdom from "jsdom"

const { JSDOM } = jsdom
global.DOMParser = new JSDOM().window.DOMParser
```

Obvously also adding `"jsdom": "^21.1.0",` to your package.json dependencies...

However, I still think the DOM should not be necessary in the first place. Or am I wrong ?
